### PR TITLE
Olympia bounty query node fixes

### LINKED ISSUE #2526: `bountyContributions` get unmapped after being withdrawn
Withdrawn contribution are not accessible in the QN throught `bountyContributions`...but they remain accessible through: `bounty.contributions`

E.g on https://3.95.67.177.nip.io/query-node/server/graphql:
```gql
query {
  bountyContributions (where: { bounty: { id_eq: 9 } }) {
    bountyId
    contributorId
  }
  bountyByUniqueInput(where: { id: 9 }) {
    id
    contributions { contributorId withdrawnInEvent { id } }
  }
}
```
Returns:
```json
{
  "data": {
    "bountyContributions": [],
    "bountyByUniqueInput": {
      "id": "9",
      "contributions": [
        {
          "contributorId": "11",
          "withdrawnInEvent": {
            "id": "OLYMPIA-126499-4"
          }
        }
      ]
    }
  }
}
```

### LINKED ISSUE #2668: Can't withdraw contributions when judgment period expired

### PR DESCRIPTION
**Pull request by thesan**
- About [keeping terminated bounties](https://github.com/Joystream/joystream/commit/a3dec3edfc67887eedd711a3a2b67f18e2e1e2ed): address Joystream/pioneer#2623, Joystream/pioneer#2637, and closes Joystream/pioneer#2526
- About [the judgement expired](https://github.com/Joystream/joystream/commit/3eb4e04d55afd2b6a2823b5fec4d6652b38e3dfb): closes Joystream/pioneer#2668
- About [`WorkSubmittedEvent.bounty`](https://github.com/Joystream/joystream/commit/49d6a9c1ec075d56739edeacfd296802de0a8ed2): address Joystream/pioneer#2413 (fix a query to count the submitted works)

### CODE REVIEW

File: query-node/mappings/src/bounty.ts [hunk 1]
```diff
@@ -187,6 +194,38 @@ function endWorkingPeriod(store: DatabaseManager, bounty: Bounty, blockNumber: n
...
+  await store.save<Bounty>(bounty)
+
+  // Update winner entries status
+  await Promise.all(
+    bounty.entries?.map((entry) => {
+      const judgment = entryJudgments.find(([entryId]) => String(entryId) === entry.id)?.[1]
+
+      if (!judgment) {
+        entry.status = new BountyEntryStatusPassed()
+      } else if (judgment?.isWinner) {
```
Comment (Lezek123) [inline query-node/mappings/src/bounty.ts]:
```suggestion
      } else if (judgment.isWinner) {
```

File: query-node/mappings/src/bounty.ts [hunk 2]
```diff
@@ -339,7 +378,6 @@ export async function bounty_BountyFundingWithdrawal({ event, store }: EventCont
     throw new Error(`Bounty contribution not found by contributor: ${actorType}`)
   }
   contribution.updatedAt = eventTime
-  contribution.deletedAt = eventTime
```
Comment (Lezek123) [inline query-node/mappings/src/bounty.ts:342]: The comment above still states: `(also update the contribution deleteAt time)`

File: query-node/mappings/src/bounty.ts [hunk 3]
```diff
@@ -187,6 +194,38 @@ function endWorkingPeriod(store: DatabaseManager, bounty: Bounty, blockNumber: n
...
+  bounty.stage = BountyStage[hasWinners ? 'Successful' : 'Failed']
+  await store.save<Bounty>(bounty)
+
+  // Update winner entries status
+  await Promise.all(
+    bounty.entries?.map((entry) => {
+      const judgment = entryJudgments.find(([entryId]) => String(entryId) === entry.id)?.[1]
+
+      if (!judgment) {
+        entry.status = new BountyEntryStatusPassed()
```
Comment (Lezek123) [inline query-node/mappings/src/bounty.ts]: You shouldn't change the status of the entries that are already in `BountyEntryStatusWithdrawn`, otherwise in Pioneer 2 there is a `Withdraw Stake` button for those entries which doesn't work:
image

**Review by Lezek123 — CHANGES_REQUESTED** [review]

**Review by Lezek123 — APPROVED** [review]
LGTM!
