### PR TITLE
addressed bug when dealing with bags during deletion

### LINKED ISSUE #2743: Channel cannot be deleted if there were no channel assets ever uploaded
**How to reproduce:**
- Create a channel without any assets using `create_channel` extrinsic
- Try to delete the channel using `delete_channel` extrinsic

**Expected result:**
Channel is deleted

**Actual result:**
`DynamicBagDoesntExist` runtime error is thrown

**Most likely cause:**
Because there are no assets provided during channel creation, no channel bag is created (https://github.com/Joystream/joystream/blob/giza/runtime-modules/content/src/lib.rs#L648), but during channel deletion the runtime still tries to delete the non-existing channel bag (https://github.com/Joystream/joystream/blob/giza/runtime-modules/content/src/lib.rs#L768), which causes an error.

### PR DESCRIPTION
**Pull request by dobertRowneySr**
fixes #2743

Went for option b

### CODE REVIEW

File: runtime-modules/storage/src/lib.rs [hunk 1]
```diff
@@ -3419,7 +3419,7 @@ impl<T: Trait> Module<T> {
     }
 
     // Check the dynamic bag existence. Static bags always exist.
-    fn ensure_bag_exists(bag_id: &BagId<T>) -> Result<Bag<T>, DispatchError> {
+    pub fn ensure_bag_exists(bag_id: &BagId<T>) -> Result<Bag<T>, DispatchError> {
```
Comment (shamil-gadelshin) [inline runtime-modules/storage/src/lib.rs]: Please, implement this method as part of the `DataObjectStorage` trait.

File: runtime-modules/content/src/lib.rs [hunk 2]
```diff
@@ -747,28 +747,31 @@ decl_module! {
...
+            // channel has a dynamic bag associated to it -> remove assets from storage
+            if let Ok(bag) = Storage::<T>::ensure_bag_exists(&bag_id) {
+                // ensure that bag size provided is valid
+                ensure!(
+                    bag.objects_number == num_objects_to_delete,
+                    Error::<T>::InvalidBagSizeSpecified
+                );
+
+                // construct collection of assets to be removed
+                let assets_to_remove: BTreeSet<DataObjectId<T>> =
```
Comment (shamil-gadelshin) [inline runtime-modules/content/src/lib.rs]: Please, implement this as a method for the `DataObjectStorage` trait. Something like `get_data_object_ids(&bag_id) -> BTreeSet`

File: runtime-modules/content/src/lib.rs [hunk 3]
```diff
@@ -747,28 +747,31 @@ decl_module! {
...
+                    &channel.deletion_prize_source_account_id
+                )?;
 
-            // delete channel dynamic bag
-            Storage::<T>::delete_dynamic_bag(
-                channel.deletion_prize_source_account_id,
-                dyn_bag
-            )?;
+                // delete channel dynamic bag
+                Storage::<T>::delete_dynamic_bag(
```
Comment (shamil-gadelshin) [inline runtime-modules/content/src/lib.rs:772]: Please, use this method through the `DataObjectStorage` trait

**Review by shamil-gadelshin — CHANGES_REQUESTED** [review]
Please, try using the `DataObjectStorage` trait to access the functionality of the `storage'  pallet. This will encapsulate dependencies and simplify future changes. 

Among other fixes please consider changing `storage::Bags::<T>::contains_key(bag_id.clone())` to `ensure_bag_exists` method.

I would suggest introducing the associated type for the `content::Trait` and access the storage subsystem using it.

File: runtime-modules/content/src/lib.rs [hunk 4]
```diff
@@ -747,28 +750,30 @@ decl_module! {
...
-                storage::DataObjectsById::<T>::iter_prefix(&bag_id).map(|x| x.0).collect();
-
-            // remove specified assets from storage
-            Self::remove_assets_from_storage(
-                &assets_to_remove,
-                &channel_id,
-                &channel.deletion_prize_source_account_id
-            )?;
+            // channel has a dynamic bag associated to it -> remove assets from storage
+            if let Ok(bag) = <T as Trait>::DataObjectStorage::ensure_bag_exists(&bag_id) {
```
Comment (shamil-gadelshin) [inline runtime-modules/content/src/lib.rs]: `T as Trait` is unnecessary. It works with just `T`.

File: runtime-modules/content/src/lib.rs [hunk 5]
```diff
@@ -1336,7 +1341,7 @@ impl<T: Trait> Module<T> {
         let dyn_bag = DynamicBagIdType::<T::MemberId, T::ChannelId>::Channel(*channel_id);
         let bag_id = BagIdType::from(dyn_bag.clone());
 
-        if !storage::Bags::<T>::contains_key(bag_id.clone()) {
+        if <T as Trait>::DataObjectStorage::ensure_bag_exists(&bag_id).is_err() {
```
Comment (shamil-gadelshin) [inline runtime-modules/content/src/lib.rs]: `T as Trait` is unnecessary. It works with just `T`.

**Review by shamil-gadelshin — CHANGES_REQUESTED** [review]
Almost there. Please fix a couple of minor issues.

**Review by shamil-gadelshin — APPROVED** [review]
LGTM
