### PR TITLE
add browse screen, fix some apollo client issues

### LINKED ISSUE #1136: Implement Browse screen, fix Apollo pagination cache
Per https://github.com/Joystream/joystream/issues/824#issuecomment-653048676 we should add a Browse screen that will allow users to explore videos in different categories

Todo:

- add some mocked data to MirageJS (categories, videos per category)
- mock the queries
- implement the view with connected data store

Blocked by #1141

### Update 14/09:
This is still WIP as during the implementation some issues with how we use Apollo cache have been identified. Some research on that alongside with fixing the existing issues has been added to the task's scope.

### PR DESCRIPTION
**Pull request by kdembler**
Resolves #1136 

Adds the Browse screen, as described [here](https://github.com/Joystream/joystream/issues/824#issuecomment-653048676). The screen (for now, for the development ease) can be accessed by clicking the "Share" button on the landing page.

Screenshot 2020-09-15 at 2 43 05 PM

### CODE REVIEW

File: atlas/packages/app/src/components/LayoutWithRouting.tsx [hunk 1]
```diff
@@ -1,17 +1,25 @@
 import React from 'react'
+import styled from '@emotion/styled'
+import { Router } from '@reach/router'
+
 import { GlobalStyle } from '@/shared/components'
-import { HomeView, VideoView } from '@/views'
+import { BrowseView, HomeView, VideoView } from '@/views'
 import routes from '@/config/routes'
-import { Router } from '@reach/router'
+import sizes from '@/shared/theme/sizes'
```
Comment (fcescob) [inline atlas/packages/app/src/components/LayoutWithRouting.tsx]: Let's be consistent with the rest of the codebase here and let's do `import {sizes} from '@/shared/theme' ` or import the theme directly

File: atlas/packages/app/src/shared/components/Placeholder/Placeholder.tsx [hunk 2]
```diff
@@ -2,14 +2,16 @@ import styled from '@emotion/styled'
...
 
 type PlaceholderProps = {
-  width?: string
-  height?: string
+  width?: string | number
+  height?: string | number
   rounded?: boolean
 }
 
+const getPropValue = (v: string | number) => (typeof v === 'string' ? v : `${v}px`)
```
Comment (fcescob) [inline atlas/packages/app/src/shared/components/Placeholder/Placeholder.tsx:10]: I'm not sure it will ever happen, but this wouldn't work with percentages.

Comment (kdembler) [reply atlas/packages/app/src/shared/components/Placeholder/Placeholder.tsx:10]: Well if you wanted to do percentages, you would need to pass the full string (e.g. `'100%'`) anyway so it will work the same way, all string will be passed through. Only numbers are interpreted as pixels

File: atlas/packages/app/src/components/LayoutWithRouting.tsx (hunk 1 above)
Comment (kdembler) [reply atlas/packages/app/src/components/LayoutWithRouting.tsx]: Certainly, fixed now

**Comment by fcescob** [comment]
LGTM!
