### PR TITLE
nft can be issued in open auction state

### LINKED ISSUE #3669: Init transactional status doesn't work with Open Auction Id
It checks for NFT existence for setting the initial auction nonce before nft is created -> bug

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1202188702226921) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by dobertRowneySr**
fixes #3669

### CODE REVIEW

File: runtime-modules/content/src/lib.rs [hunk 1]
```diff
@@ -2290,7 +2290,7 @@ impl<T: Trait> Module<T> {
     /// Convert InitTransactionalStatus to TransactionalStatus after checking requirements on the Auction variant
     fn ensure_valid_init_transactional_status(
         init_status: &InitTransactionalStatus<T>,
-        video_id: T::VideoId,
+        _video_id: T::VideoId,
```
Comment (bedeho) [inline runtime-modules/content/src/lib.rs:2293]: Remove unused param.

**Review by bedeho — APPROVED** [review]
LGTM.
