### PR TITLE
Master fix member channel nft proceeds effectively credited

### LINKED ISSUE #3762: NFT Channel with no reward account and member owned has funds burned
TSIA

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1202299719378625) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by dobertRowneySr**
fixes #3762

No code has been lost, it is just that changes in https://github.com/Joystream/joystream/issues/3650 have never been implemented. Royalty payment was working correctly however

##### Changes
1. there is a test to check the above violation (NFT owned by channel, channel owned by member, and reward account not set) for each of the possible nft revenue event:
- Auction, both english and open use the same` complete_auction` internal logic hence they can be treated as equal in this respect
- Buy Now 
- Accept NFT Offer
2. `ensure_owner_account_id` has been renamed to `ensure_nft_owner_account_id` and internally uses `ensure_reward_account`, effectively implementing the business logic desired: https://github.com/Joystream/joystream/issues/3650
3. same thing as `build_royalty_payment` which worked correctly already, I just refactored it by reusing the `ensure_reward_account` method

### CODE REVIEW

File: runtime-modules/content/src/nft/mod.rs [hunk 1]
```diff
@@ -382,15 +382,23 @@ impl<T: Trait> Module<T> {
...
         channel_id: T::ChannelId,
         nft: &Nft<T>,
     ) -> Result<T::AccountId, DispatchError> {
         match nft.owner {
             NftOwner::Member(member_id) => T::MemberAuthenticator::controller_account_id(member_id),
-            NftOwner::ChannelOwner => Self::channel_by_id(channel_id)
-                .reward_account
-                .ok_or_else(|| Error::<T>::RewardAccountIsNotSet.into()),
+            NftOwner::ChannelOwner => {
+                let channel = Self::ensure_channel_exists(&channel_id)?;
```
Comment (bedeho) [inline runtime-modules/content/src/nft/mod.rs]: 1. This method needs a better name, lets call it `ensure_nft_owner_has_beneficiary_account`.
2. It should not fail statically on reading channel from storage, please see general comment in primary review comment. Hence make `channel` a method parameter which is read using `video.channel_id` infallibly in extrinsic scope after video has been confirmed to exist.

File: runtime-modules/content/src/nft/mod.rs [hunk 2]
```diff
@@ -382,15 +382,23 @@ impl<T: Trait> Module<T> {
...
+                Self::ensure_reward_account(&channel)
```
Comment (bedeho) [inline runtime-modules/content/src/nft/mod.rs]: Can we rename `ensure_reward_account` to `ensure_channel_has_beneficiary_account`.

**Review by bedeho — CHANGES_REQUESTED** [review]
Overall looks good, but lets have @Lezek123 also review.

In various places we do `channel_by_id` reads inside various methods, and if these are called at the wrong time, where the channel is not guaranteed to exist, then this will create storage side-effect in such methods, so this is a bit risky in terms of future maintainers. It would be safer to just pass in `channel` objects directly to such methods, and then to read such objects in extrinsic scope using `channel_by_id(video.channel_id)` after it has been established that the video exists. This is less likely to break in the future.

File: runtime-modules/content/src/nft/mod.rs (hunk 1 above)
Comment (dobertRowneySr) [reply runtime-modules/content/src/nft/mod.rs]: addressed in 8d223f3594daea61e53289ee82f1080bbe8c1e9b

File: runtime-modules/content/src/nft/mod.rs (hunk 2 above)
Comment (dobertRowneySr) [reply runtime-modules/content/src/nft/mod.rs]: addressed in 8d223f3594daea61e53289ee82f1080bbe8c1e9b

**Review by bedeho — APPROVED** [review]
LGTM.

File: runtime-modules/content/src/tests/nft/accept_incoming_offer.rs [hunk 3]
```diff
@@ -228,31 +234,31 @@ fn accept_incoming_offer_reward_account_burns_token_with_curator_owner_channel()
...
-        increase_account_balance_helper(DEFAULT_MEMBER_ACCOUNT_ID, INITIAL_BALANCE);
-        increase_account_balance_helper(SECOND_MEMBER_ACCOUNT_ID, DEFAULT_NFT_PRICE);
-        create_default_member_owned_channel_with_video();
+        let curator_group_id = curators::add_curator_to_new_group(DEFAULT_CURATOR_ID);
+        let video_id = Content::next_video_id();
+        let curator_actor = ContentActor::Curator(curator_group_id, DEFAULT_CURATOR_ID);
+        CreateChannelFixture::default()
+            .with_sender(DEFAULT_CURATOR_ACCOUNT_ID)
+            .with_actor(curator_actor)
+            .call();
```
Comment (Lezek123) [inline runtime-modules/content/src/tests/nft/accept_incoming_offer.rs:243]: The method name should be _accept_incoming_offer\_**with_no**\_reward_account_burns_token_with_curator_owner_channel_

**Comment by mnaamani** [comment]
Please apply cargo fmt: `cargo-fmt --all` to fix code formatting checks

**Comment by mnaamani** [comment]
Also make sure to run `yarn cargo-checks` to run all linter and formatting checks. One fix it shows is needed:

```
yarn cargo-checks
yarn run v1.22.15
$ ./devops/git-hooks/pre-commit && ./devops/git-hooks/pre-push
running rust-fmt
running clippy (rust linter)
   Compiling chain-spec-builder v6.7.0 (/Users/mokhtar/joystream/joystream/utils/chain-spec-builder)
   Compiling joystream-node-runtime v10.7.0 (/Users/mokhtar/joystream/joystream/runtime)
    Checking pallet-content v3.2.0 (/Users/mokhtar/joystream/joystream/runtime-modules/content)
   Compiling joystream-node v6.7.0 (/Users/mokhtar/joystream/joystream/node)
error: unused import: `frame_support::storage::StorageValue`
 --> runtime/src/runtime_api.rs:2:5
  |
2 | use frame_support::storage::StorageValue;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `-D unused-imports` implied by `-D warnings`

error: aborting due to previous error

error: could not compile `joystream-node-runtime`

To learn more, run the command again with --verbose.
error Command failed with exit code 101.

```

**Review by Lezek123 — APPROVED** [review]
The change looks ok, but I think in general the nft tests need some refactorization (probably not as part of this PR though).

There are quite a lot of combinations that need to be tested in order to make sure everything works as expected:

**Ways to buy/acquire nft:**
- through open auction (winner picked)
- through open auction (buy now price hit)
- through english auction (settle)
- through english auction (buy now price hit)
- through `accept_incoming_offer`
- through `buy_nft`

For each of those we can have any combination of:

**NFT owner beeing:**
- a member
- a member channel w/ reward account set (original issuer)
- a member channel w/ reward account not set (original issuer)
- a curator channel w/ reward account set (original issuer)
- a curator channel w/ reward account not set (original issuer)

**Video owner (royalty reciever) beeing:**
- a member channel w/ reward account set
- a member channel w/ reward account not set
- a curator channel w/ reward account set
- a curator channel w/ reward account not set

If we wanted to test all possible combinations, that's 48 separate test cases (assuming we always use `Some(_)` royalty to test that part too).

Manually writing each test case would be quite cumbersome, but I think it would be possible to make some shared setup for initializing and testing all possible channel / nft owners and just have one test like `buy_nft_all_combinations_ok` for each of the 6 ways the nft can be acquired.

Some mock code example to ilustrate what I have in mind:
```
let channels = [
            {
                sender: DEFAULT_MEMBER_ACCOUNT_ID,
                actor: ContentActor::Member(DEFAULT_MEMBER_ID))
                reward_account: None,
                expected_royalty_dst: DEFAULT_MEMBER_ACCOUNT_ID,
            },
            {
                sender: DEFAULT_MEMBER_ACCOUNT_ID,
                actor: ContentActor::Member(DEFAULT_MEMBER_ID))
                reward_account: Some(DEFAULT_MEMBER_CHANNEL_REWARD_ACCOUNT_ID),
                expected_royalty_dst: DEFAULT_MEMBER_CHANNEL_REWARD_ACCOUNT_ID,
            },
            {
                sender: DEFAULT_CURATOR_ACCOUNT_ID,
                actor: ContentActor::Curator(group_id, DEFAULT_CURATOR_ID))
                reward_account: None,
                expected_royalty_dst: None,
            },
            {
                sender: DEFAULT_CURATOR_ACCOUNT_ID,
                actor: ContentActor::Curator(group_id, DEFAULT_CURATOR_ID))
                reward_account: Some(DEFAULT_CURATOR_CHANNEL_REWARD_ACCOUNT_ID),
                expected_royalty_dst: DEFAULT_CURATOR_CHANNEL_REWARD_ACCOUNT_ID,
            },            
]
```

Now for each of `channels` you want to setup the nft owner to be either the original channel, or `OTHER_MEMBER`.

If the owner is the channel then `expected_payment_dst = expected_royalty_dst`, otherwise `expected_payment_dst = OTHER_MEMBER_ACCOUNT_ID`.

You could reuse a setup like this (creating channel, issuing nft w/ a specific owner) and final assertions for all 6 scenarios through which the nft can be acquired, making the number of test smaller and the tests themselves quite clear and complete.
