### PR TITLE
Colossus: verify bag <-> bucket assignment

### LINKED ISSUE #4292: Colossus: verify bag<>bucket assignment before sending accept extrinsic
## Problem
It seems at the moment, when finalizing upload, Colossus will only verify that the `storageBucketId` sent with the request is assigned to the worker that operates the node. However, it will not verify that the `bagId` provided with the request actually belongs to specified `storageBucketId`. That validation happens on chain though, so if I provide wrong input, Colossus will try to send accept extrinsic which will fail and since Colossus doesn't understand what happened it will provide only `Extrinsic failed` message in the response, which is enigmatic and doesn't help with debugging.

## Proposal
We should do this pre-validation of correct bag<>bucket assignment before trying to send accept extrinsic and if the validation fails, provide meaningful error message to the user

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203011489083273) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by zeeshanakram3**
fixes #4292

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203197954194485) by [Unito](https://www.unito.io)

### CODE REVIEW

File: storage-node/src/services/webApi/controllers/filesApi.ts [hunk 1]
```diff
@@ -99,13 +99,15 @@ export async function uploadFile(
     const queryNodeUrl = res.locals.queryNodeEndpoint
     const workerId = res.locals.workerId
 
-    const [, hash] = await Promise.all([
+    const api = res.locals.api
+    const bagId = parseBagId(uploadRequest.bagId)
+
+    const [, , hash] = await Promise.all([
       verifyBucketId(queryNodeUrl, workerId, uploadRequest.storageBucketId),
+      verifyBagAssignment(api, bagId, uploadRequest.storageBucketId),
```
Comment (Lezek123) [inline storage-node/src/services/webApi/controllers/filesApi.ts:107]: It looks like `RequestData` is incorrectly typed, the `storageBucketId` type was set to `number`, but in `api-spec/openapi.yaml` it's defined as `string`:
```yaml
              properties:
                file:
                  description: Data file
                  type: string
                  format: binary
                dataObjectId:
                  description: Data object runtime ID
                  type: string
                  pattern: '^\d+$' #integer
                storageBucketId:
                  description: Storage bucket ID
                  type: string
                  pattern: '^\d+$' #integer
                bagId:
                  description: Bag ID
                  type: string
```
There may be more mistakes like this. Ideally those types would be just autogenerated from `openapi.yml` spec, I'll make an issue to fix this.

The bottom line is that `verifyBagAssignment` now always fails because it compares `number` bucket ids to a `string` bucket id:
```
Uploading object 0 (/home/leszek/projects/joystream/joystream-ws-4/cli/examples/content/cover-photo-)
Chosen storage node endpoint: http://172.18.0.1:3333/api/v1
Uploading object 1 (/home/leszek/projects/joystream/joystream-ws-4/cli/examples/content/avatar-photo)
 ›   Warning: Upload of object 0 failed: Unexpected error when trying to upload a file: 
 ›   {"type":"upload","message":"Error: Storage bag {\"dynamic\":{\"channel\":1}} is not assigned to
 ›    storage bucket 0."}
 ›   Warning: Upload of object 1 failed: Unexpected error when trying to upload a file: 
 ›   {"type":"upload","message":"Error: Storage bag {\"dynamic\":{\"channel\":1}} is not assigned to
 ›    storage bucket 0."}
 ›   Warning: Some assets were not uploaded successfully. Try reuploading them with 
 ›   content:reuploadAssets!
```

**Review by Lezek123 — CHANGES_REQUESTED** [review]

**Comment by bedeho** [comment]
This can only stay in mainnet scope if

1) It has 0 impact on downstream dependencies, like Atlas, QN, CLI, tests...
2) We truly believe this can be shipped without augmenting our QA plans

@zeeshanakram3 what do you think?

**Comment by zeeshanakram3** [comment]
> 1. It has 0 impact on downstream dependencies, like Atlas, QN, CLI, tests...
> 2. We truly believe this can be shipped without augmenting our QA plans

1. This specific PR does not impact the downstream dependencies
2. Sorry, I am not fully update to date with the QA plans but since this change (which includes only extra validation) is only local to Colossus, I believe it wont affect the QA plan

File: storage-node/src/services/webApi/controllers/filesApi.ts (hunk 1 above)
Comment (zeeshanakram3) [reply storage-node/src/services/webApi/controllers/filesApi.ts:107]: Since #4402 supersedes this PR now, maybe we can ignore this PR and only merge #4402?
