### PR TITLE
prevent multiple active applications by a member to an opening

### LINKED ISSUE #163: Accepting multiple applications for same member causes assertion failure
**Problem**

The same member can apply more than once to an opening in the curator working group.
An assertion failure is occurring when the lead accepts more than one application for the same member because of a failed attempt to register the same role more than once on the member.

https://github.com/Joystream/substrate-runtime-joystream/blob/c63a02d922c46d11387b5e26df5dab00ec8d864a/src/content_working_group/lib.rs#L1594

This edge case was not accounted for.

**Solutions**
1. Prevent same member from applying more than once - if applican't wishes to perhaps increase their stake during the application process they must withdraw their application first then re-apply.

2. In fill_curator_opening() guard against successful_curator_application_ids set having applications from same member id.

3. Ensure there is always only one application per member per opening: When same member applies a second time to an opening, the new application replaces the old one.

I like Option 3 but this will require some changes in the UI/Hiring-Flow in pioneer. So I think I will prepare a fix with option 1.

### PR DESCRIPTION
**Pull request by mnaamani**
Fixes #163

### CODE REVIEW

File: src/content_working_group/lib.rs [hunk 1]
```diff
@@ -2055,6 +2060,29 @@ impl<T: Trait> versioned_store_permissions::CredentialChecker<T> for Module<T> {
 }
 
 impl<T: Trait> Module<T> {
+    fn ensure_member_has_no_active_application_on_opening(
+        opening_id: CuratorOpeningId<T>,
+        member_id: T::MemberId,
+    ) -> Result<(), &'static str> {
+        for (_id, curator_application) in <CuratorApplicationById<T>>::enumerate() {
```
Comment (bedeho) [inline src/content_working_group/lib.rs]: This iterates all applications on all openings, which is not great, or entirely safe.

At the very least there is `CuratorOpening::curator_applications` of type `BTreeSet<CuratorApplicationId>` which allows you to iterate only applications to the given curator opening. This is still not _great_, but we will do a refactor later where membership binding is done inside subsystem modules, not in membership module, which would make the lookup direct, so this may be the best we can do for now, short of introducing a temporary reverse index.
