### PR TITLE
Mainnet liberated integration test fix

### LINKED ISSUE #4401: Integration Tests without Sudo calls
After main net is deployed, the sudo pallet will be removed from the runtime.
Many Integration/Network tests depend on sudo pallet for putting the runtime in certain states or bypassing the council. These tests will all break see: https://github.com/Joystream/joystream/pull/4400

The tests need to be updated to work around this limitation.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1203661753438153) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by dobertRowneySr**
# Intro & Scope
Fixes integration tests after the removal of the sudo pallet as prescribed in #4401 

# Details
- [x] replace sudo jobs with proposals
- [x] merged into `mainnet-liberated`
- [x] generated types and metadata

# Tech debt
I think a refactoring is needed in order to encapsulate Proposal Creation + Proposal Execution in one subclass of `BaseQueryNodeFixture`. If you think it's urgent I'll do it as part of this PR review iteration, otherwise I'll create a issue for the future

# Next steps
Merging the resulting PR into `Ephesus`: #4556

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1203780568380191) by [Unito](https://www.unito.io)

### CODE REVIEW

File: tests/network-tests/src/fixtures/proposals/DecideOnProposalStatusFixture.ts [hunk 1]
```diff
@@ -215,4 +217,48 @@ export class DecideOnProposalStatusFixture extends BaseQueryNodeFixture {
...
   }
+
+  public async getExecutionEvents(section: string, method: string) {
+    const qProposals = await this.query.tryQueryWithTimeout(
+      () => this.query.getProposalsByIds(this.params.map((p) => p.proposalId)),
+      (res) => this.assertProposalStatusesAreValid(res)
+    )
+    const executionBlocks = await Promise.all(
+      this.proposals.map(async (proposal, i) => {
+        const qProposal = qProposals[i]
```
Comment (mnaamani) [inline tests/network-tests/src/fixtures/proposals/DecideOnProposalStatusFixture.ts:228]: There is a potential problem with this assignment since qProposals will contain all proposals every created, and this.proposals is only the proposals that are currently active in chain state. It would be more correct to pick from qProposals the proposal with the matching proposalId.

File: tests/network-tests/src/fixtures/workingGroups/CreateLeadOpeningFixture.ts [hunk 2]
```diff
@@ -0,0 +1,166 @@
...
+  }
+
+  protected assertQueryNodeEventIsValid(qEvent: OpeningAddedEventFieldsFragment, i: number): void {
+    assert.equal(qEvent.group.name, this.group)
+    assert.equal(qEvent.opening.runtimeId, this.events[i].event.data[0].toNumber())
+  }
+
+  async runQueryNodeChecks(): Promise<void> {
+    await super.runQueryNodeChecks()
+    // Query the events
```
Comment (mnaamani) [inline tests/network-tests/src/fixtures/workingGroups/CreateLeadOpeningFixture.ts:142]: best to remove commented out code

File: tests/network-tests/src/scenarios/full.ts [hunk 3]
```diff
@@ -79,12 +74,9 @@ scenario('Full', async ({ job, env }) => {
   ]).requires(councilFailuresJob)
 
   // Working groups
-  // Before any other jobs hire then terminate all WG leads
-  const terminateLeadsJob = job('terminate working-group leads', terminateLeads).after(
-    job('sudo lead opening', leadOpening(process.env.IGNORE_HIRED_LEADS === 'true')).after(proposalsJob)
+  const sudoHireLead = job('sudo lead opening', leadOpening(process.env.IGNORE_HIRED_LEADS === 'true')).after(
```
Comment (mnaamani) [inline tests/network-tests/src/scenarios/full.ts]: the "sudo" in the name of this job doesn't make sense anymore

**Review by mnaamani — CHANGES_REQUESTED** [review]
Overall looks great, well done. I left my concern about assumption being made about result of proposals query from chain state and query node which will not always hold. So it would be better to address now, otherwise it might be hard to debug failing proposals test in future.

Although running the integration tests locally didn't cause a problem.

**Comment by mnaamani** [comment]
Additional points:
we should add back the setupNewChain, and setupNewChainMultiStorage scenarios to `run_test_scenarios` job in github workflow run-network-tests.

Also update some of the bash scripts in tests/network-tests/ that still have some reference to sudo arguments and env variables which are not required anymore, and dropping the SUDO_ACCOUNT_URI from .env file

**Comment by dobertRowneySr** [comment]
I have addressed all the required comments.
There where still some outdated `sudo` references, mostly in the form of `asSudo` boolean for WG tests.
They are removed now

**Comment by ignazio-bovo** [comment]
I have addressed all the required comments.
There where still some outdated `sudo` references, mostly in the form of `asSudo` boolean for WG tests.
They are removed now

File: tests/network-tests/src/flows/membership/invitingMembers.ts [hunk 4]
```diff
@@ -18,6 +22,37 @@ export default async function invitingMembers({ api, query, env }: FlowProps): P
   await new FixtureRunner(buyMembershipHappyCaseFixture).run()
   const [inviterMemberId] = buyMembershipHappyCaseFixture.getCreatedMembers()
 
+  // Membership WG balance required
```
Comment (mnaamani) [inline tests/network-tests/src/flows/membership/invitingMembers.ts:25]: Since this flow could be used in other scenarios where perhaps a council was not elected, maybe it should fail early.

File: tests/network-tests/src/flows/membership/invitingMembers.ts [hunk 5]
```diff
@@ -18,6 +22,37 @@ export default async function invitingMembers({ api, query, env }: FlowProps): P
...
+      title: 'Proposal to set budget',
+      description: `Proposal to set budget for membership working group`,
+    },
+  ])
+  await new FixtureRunner(updateWgBudgetProposalFixture).run()
+  const [updateWgBudgetProposalId] = updateWgBudgetProposalFixture.getCreatedProposalsIds()
+  const decideOnUpdateWgBudgetProposalStatusFixture = new DecideOnProposalStatusFixture(api, query, [
+    { proposalId: updateWgBudgetProposalId, status: 'Approved', expectExecutionFailure: false },
+  ])
+  await new FixtureRunner(decideOnUpdateWgBudgetProposalStatusFixture).run()
```
Comment (mnaamani) [inline tests/network-tests/src/flows/membership/invitingMembers.ts:53]: Will the fixture fail if there is no council to actually vote on the proposal?

**Review by mnaamani — APPROVED** [review]
